default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_USER_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_DEVELOPMENT'] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB_TEST'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB_PRODUCTION'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['DEVELOPER_WEAR_DATABASE_PASSWORD'] %>
